### ISSUE TITLE
[BUG] Timeout on SSH tunnels

### ISSUE THREAD

**Issue by ppseprus** [cweijan/vscode-mysql#642]
- OS: MacOS
- Database Type: PostgreSQL and MySQL

This is not —yet— a bug report... Is it possible that since yesterday (20th) the SSH tunneling broke? 🤔 

I cannot figure out when VSC updates extension.
I cannot see the logs while the connection is being built up.

I only see a connection timeout, even though
- Our servers are running fine (checked with ops), and
- The extension works fine on localhost

The saved configurations for this particular connection has been working for months. Even yesterday.
Today I cannot access anything...

**Comment by cweijan** [comment]
Hi, if there is an error, open the developer tools to see the details.
![image](https://user-images.githubusercontent.com/27798227/180223015-dc6296a4-343c-4cae-be9d-f6a305e83e88.png)

For the ssh tunnel, I did make some modifications recently, but it shouldn't affect the existing connection, try to recreate the connection.

**Comment by ppseprus** [comment]
The debug console is completely empty.

And as of now, I can confirm that the issue is with the extension.
I managed to setup a tunnel via my terminal and I was able to connect to the database on `localhost:8003`, using the extension. 

`ssh -L 8003:127.0.0.1:7400 x.x.x.x`

**Comment by cweijan** [comment]
Another possibility is that the socket path in your connection is not empty. In the new version, I forwarded the socket_path.
![image](https://user-images.githubusercontent.com/27798227/180229589-9cbdf61a-9ed3-442f-8a93-4b9cd525505b.png)
Finally please try to recreate the mysql connection.

**Comment by ppseprus** [comment]
I do not have a Socket Path

<img width="899" alt="Screenshot 2022-07-22 at 13 33 35" src="https://user-images.githubusercontent.com/1323285/180431305-403eac01-90cd-428e-963a-54afe34e3594.png">

**Comment by ppseprus** [comment]
Checked the Connection Configuration JSON and there's no socket path set for these connections.

**Comment by cweijan** [comment]
Could you try to create an ssh connection with this extension? In the latest version I specified the key exchange algorithm for ssh, maybe because of this.

**Comment by cweijan** [comment]
And try to install the old version of the extension, I didn't encounter your situation with the new version, sorry.
![image](https://user-images.githubusercontent.com/27798227/180588270-cc37d553-574c-4377-bc2e-f97238c3805f.png)

**Comment by ppseprus** [comment]
Works on `5.6.2`, but breaks on `5.6.3` and above...

**Comment by ppseprus** [comment]
>In the latest version I specified the key exchange algorithm for ssh, maybe because of this.

The latest `5.6.5` also does not work.

**Comment by cweijan** [comment]
Hi, regarding the ssh tunnel, after version 5.6.3 I added forwarding authentication and specified encryption algorithm, I am sorry for the current situation, you need to do the following to help me solve this problem:
1. Try to modify the connection timeout
2. Create a ssh connection to see if the connection is successful.

**Comment by ppseprus** [comment]
Changed the timeout from the default 5000 to 10000 and 20000.
In both cases:
* the debug console is completely empty, and
* I get a timeout

<img width="332" alt="Screenshot 2022-07-26 at 10 10 21" src="https://user-images.githubusercontent.com/1323285/180956884-20d92e95-29d7-405b-8df1-45527b79f1d6.png">

Here's my redacted config
```json
{
  "1639598927952": {
    "host": "127.0.0.1",
    "port": 7400,
    "user": "user",
    "password": "pasword",
    "timezone": "+00:00",
    "ssh": {
      "host": "host",
      "privateKeyPath": "pathToKey",
      "port": 22,
      "username": "username",
      "type": "privateKey",
      "connectTimeout": "20000",
      "algorithms": {},
      "passphrase": "passphrase"
    },
    "usingSSH": true,
    "esAuth": "none",
    "encoding": "utf8",
    "global": true,
    "dbType": "MySQL",
    "encrypt": true,
    "authType": "default",
    "name": "name",
    "index": 5,
    "savePassword": true,
    "connectTimeout": 20000
  }
}
```

**Comment by ppseprus** [comment]
>Here's my redacted config

At least one of them 😅

**Comment by cweijan** [comment]
Can you create an ssh connection with your ssh tunnel configuration.
![image](https://user-images.githubusercontent.com/27798227/180958648-a065b2d2-f4d8-4b09-886d-38716b6ad694.png)

**Comment by ppseprus** [comment]
Nope. Its not working either.

Is there way to get the logs? I cannot get anything to show up and its really frustrating. 🤔

**Comment by ppseprus** [comment]
I also tried to just recreate the connection. Again, not working.

**Comment by cweijan** [comment]
Hi, I released version 5.6.6, try it.

**Comment by ppseprus** [comment]
Okay. So now, on 5.6.6,

* I was able to establish an SSH connection, creating a completely new connection
* Suddenly, the updated PostgreSQL connected started working, however,
  * Without any increase to the connection timeout
* The MySQL connection (on the same remote machine) still throws a timeout
  * I double checked, and using `ssh -L 8003:127.0.0.1:7400 x.x.x.x` to tunnel in, I can connect to the database on my local machine — which meant the DB is up and running
  * Increasing the connection timeout also did not resolve this issue

So.. seemed like I have two configs, both tunneling into the same machine, everything is the, but still: one works while the other does not.

That obviously does not make any sense.

So finally, I figured out. My private key is not `id_rsa`, which means that something broke things at the release `5.6.3` — does that make sense?

I went back and checked the previous versions and obviously, now they work.

I tried to rethink what I did, thinking "maybe I messed up somehow", but one day I was using them, went to bed, and the next morning they were not working...

I dont know. As far as the original reporting is considered, this BUG is resolved on my end.

**Comment by ppseprus** [comment]
**Edit: The configs all pointed to the default ~/.ssh/id_rsa file — which I never even had. And I had one tunnel open that probably allowed the PostgreSQL to connect somehow. When I killed that tunneling, even that failed.**

**Comment by ppseprus** [comment]
Would be great to have some console logs — this would have been easy to debug if simply the key was missing for some reason... 🤔

**Comment by cweijan** [comment]
Hi, thanks for your feedback, I specified the key exchange algorithm for ssh after 5.6.3, maybe your server openssh version is old.

As for the key, maybe because your key path contains `~`, the extension doesn't support parsing to user path currently.

I only printed the error log before, this is my oversight, I will adding debug log in the future

**Comment by ppseprus** [comment]
Anyways! Thanks a lot for helping me resolve this! 😃
