### ISSUE TITLE
[BUG]MySQL Procedure

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#957]
- Operating system: Windows 10
- Database type and version: MySQL 8.0.28

To store a package, earlier I used to select the full package and execute Run Selected SQL and it works perfectly.

Now I am getting three issues:

1. Header of the procedure is as follows:

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/565ea8c2-a6fe-4d16-832e-cfa39d5d9297)

Now I am getting the error - PROCEDURE ENGINE_LINK_BUTTON_673 already exists.  Earlier it first execute drop command and then create the procedure

2. A message box as follows pops up

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/95333c88-d3d0-4f7e-8675-47517c1f1f4d)

If I proceed without entering any value, it procedure is not getting created

3. If I try to create the procedure while standing in Line No - 1000, after creating the procedure the focus moves to the first line.  This issue exists during the past one or two months.  Earlier also this issue has come and it is settled after I reported this error

Request you to please rectify these errors.  I am using Functions and Procedures extensively in MySQL database.

Thanks and Regards

Franklin KF

**Comment by cweijan** [comment]
Hi, the first error is in 6.8.0, please try version 6.8.1, I have fixed it in this version.

**Comment by cweijan** [comment]
Hi, please try the latest version 6.8.2, I have fixed the issues you mentioned.

And you can try to undisable codelen. In a previous version, I have enhanced the extension's ability to parse DDL.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/0cd2c7e4-03b3-420c-8ba2-57c6afcf95d7)

**Comment by cweijan** [comment]
Hi, does the new version solve your problem?

**Comment by franklinkf** [comment]
Sir,

Still I am in 6.8.1 version.  6.8.2 was not updated

**Comment by cweijan** [comment]
Please click the refresh button after restarting vscode.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/b63b3abe-6bbd-45a8-b5e5-11f634d43b68)

**Comment by franklinkf** [comment]
No Sir, still the same

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/800a320c-854c-472d-8d92-7a6922e87973)

**Comment by cweijan** [comment]
Sorry, my release a few days ago didn't seem to be successful, I have now released version 6.8.2.

**Comment by franklinkf** [comment]
Great.  Now I updated to 6.8.2 and all the issues reported are settled.

Also, I have enabled SQL Code Lens. Now the issue why I disabled it earlier has gone.  Earlier in Procedures and functions, Execute option is displayed against each and every syntax.  Now it is coming properly ie. only at the beginning of the procedure

Thank you Sir.  Appreciate your great work.

Thanks and regards,

Franklin

**Comment by cweijan** [comment]
Thanks feedback.

**Comment by franklinkf** [comment]
> Great. Now I updated to 6.8.2 and all the issues reported are settled.
> 
> Also, I have enabled SQL Code Lens. Now the issue why I disabled it earlier has gone. Earlier in Procedures and functions, Execute option is displayed against each and every syntax. Now it is coming properly ie. only at the beginning of the procedure
> 
> Thank you Sir. Appreciate your great work.
> 
> Thanks and regards,
> 
> Franklin

Regarding Code Lens, after refreshing VS Code, the execute option is coming against every syntax inside the procedures and functions

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/802c3c8f-0250-49df-a268-c907285019c6)


If this is the intended behavior, I can disable it. No problem.

**Comment by cweijan** [comment]
Yes, it seems you still need to disable it, because oracle and mysql have syntax conflicts, it can only work properly when the oracle connection is activated, I will continue to optimize it in the future.

**Comment by franklinkf** [comment]
OK Sir. Thank You
